apiVersion: apps/v1
kind: Deployment
metadata:
  name: sunofundosapideploy
spec:
  selector:
    matchLabels:
      app: sunofundosapideploy
  replicas: 1 
  template: 
    metadata:
      labels:
        app: sunofundosapideploy
    spec:
      containers:
      - name: sunofundosapideploy
        image: thiagoguaru/sunofundosapi:latest
        ports:
        - containerPort: 80
--- 
apiVersion: v1
kind: Service
metadata:
 name: sunofundosapi
spec:
 type: NodePort
 selector:
   app: sunofundosapi
 ports:
   - name: client
     protocol: TCP
     port: 80
     nodePort: 30080
 selector:
   app: sunofundosapi
