apiVersion: apps/v1
kind: Deployment
metadata:
  name: sunofundosapi
spec:
  selector:
    matchLabels:
      app: sunofundosapi
  replicas: 1 
  template: 
    metadata:
      labels:
        app: sunofundosapi
    spec:
      containers:
      - name: sunofundosapi
        image: thiagoguaru/sunofundosapi:latest
        ports:
        - containerPort: 80
---
apiVersion: v1
kind: Service
metadata:
 name: sunofundosapi
spec:
 type: NodePort
 selector:
   app: sunofundosapi
 ports:
   - name: client
     protocol: TCP
     port: 80
     nodePort: 32080
 selector:
   app: sunofundosapi